spring:
  datasource:
    url: ${PSQLDB_URL:jdbc:postgresql://localhost:5432/payment_db}
    username: ${PSQLDB_NAME:postgres}
    password: ${PSQLDB_PASSWORD:password}

  jpa:
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092