server:
  port: 8081
spring:
  application:
    name: payment-ms
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

kafka:
  topics:
    payment-result: payment-result-topic
    convert-result: convert-result-topic
    document-result: document-result-topic

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /v3/api-docs

currency:
  rates:
    USD_EUR: 0.92
    USD_AZN: 1.70
    EUR_USD: 1.09
    EUR_AZN: 1.85
    AZN_USD: 0.59
    AZN_EUR: 0.54
    AZN_TRY: 26.31
    TRY_AZN: 0.038

payment:
  fee:
    percentage: 1.5

logging:
  level:
    liquibase: info