spring:
  datasource:
    url: ${DOCKER_PSQLDB_URL:jdbc:postgresql://localhost:5432/payment_db}
    username: ${DOCKER_PSQLDB_NAME:postgres}
    password: ${DOCKER_PSQLDB_PASSWORD:password}
#    url: ${LOCAL_PSQLDB_URL:jdbc:postgresql://localhost:5432/payment_db}
#    username: ${LOCAL_PSQLDB_NAME:postgres}
#    password: ${LOCAL_PSQLDB_PASSWORD:password}

  jpa:
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092